services:

  profile_match_database:
    image: postgres:latest
    container_name: profile_match_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-profile_matcher_db}
    networks:
      - profile_match_network

  profile_matcher_test_database:
    image: postgres:latest
    container_name: profile_matcher_test_database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER:-test}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD:-test}
      POSTGRES_DB: ${TEST_DATABASE_NAME:-profile_matcher_test_db}
    networks:
      - profile_match_network

  profile_matcher_api:
    depends_on:
      - profile_match_database
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      API_HOST: ${API_HOST:-localhost}
      API_PORT: ${API_PORT:-8080}
      LOG_LEVEL: ${LOG_LEVEL}
      DATABASE_HOST: host.docker.internal
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
    networks:
      - profile_match_network

networks:
  profile_match_network:
    driver: bridge

    