services:

  profile_match_database:
    image: postgres:latest
    container_name: profile_match_database
    # env_file: 
    #   # - path: ".vscode/.env"
    #   - path: "./.env"
    #   - required: true
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      #TODO: fix this to use environment variables from .env file
      # POSTGRES_USER: ${DATABASE_USER}
      # POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # POSTGRES_DB: ${DATABASE_NAME}

      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: profile_matcher_db
    networks:
      - profile_match_network

networks:
  profile_match_network:
    driver: bridge  
    