"""Add player profile and current campaign tables

Revision ID: 8e92db4c2bef
Revises: 
Create Date: 2025-07-14 19:39:52.913602

"""
from typing import Sequence, Union
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Table
import os


# revision identifiers, used by Alembic.
revision: str = '8e92db4c2bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CURRENT_CAMPAIGNS_MOCK_DATA: str = os.getenv(
    "CURRENT_CAMPAIGNS_MOCK_DATA", "_NOT_SET_")
PLAYER_PROFILES_MOCK_DATA: str = os.getenv(
    "PLAYER_PROFILES_MOCK_DATA", "_NOT_SET_")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    current_campaigns_table: Table = op.create_table('current_campaigns',
                                                     sa.Column('id', sa.Integer(),
                                                               autoincrement=True, nullable=False),
                                                     sa.Column(
                                                         'name', sa.String(), nullable=False),
                                                     sa.Column(
                                                         'game', sa.String(), nullable=False),
                                                     sa.Column(
                                                         'priority', sa.Float(), nullable=False),
                                                     sa.Column(
                                                         'matchers', sa.JSON(), nullable=False),
                                                     sa.Column(
                                                         'enabled', sa.Boolean(), nullable=False),
                                                     sa.Column(
                                                         'start_date', sa.String(), nullable=False),
                                                     sa.Column(
                                                         'end_date', sa.String(), nullable=False),
                                                     sa.Column(
                                                         'last_updated', sa.String(), nullable=False),
                                                     sa.Column('date_created', sa.DateTime(),
                                                               server_default=sa.text('now()'), nullable=False),
                                                     sa.Column('date_updated', sa.DateTime(),
                                                               server_default=sa.text('now()'), nullable=False),
                                                     sa.Column(
                                                         'date_deleted', sa.DateTime(), nullable=True),
                                                     sa.PrimaryKeyConstraint(
                                                         'id'),
                                                     sa.UniqueConstraint('id')
                                                     )
    player_profiles_table: Table = op.create_table('player_profiles',
                                                   sa.Column('id', sa.Integer(),
                                                             autoincrement=True, nullable=False),
                                                   sa.Column(
                                                       'player_id', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'credential', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'created', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'modified', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'last_session', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'total_spent', sa.Float(), nullable=False),
                                                   sa.Column(
                                                       'total_refund', sa.Float(), nullable=False),
                                                   sa.Column('total_transactions',
                                                             sa.Float(), nullable=False),
                                                   sa.Column(
                                                       'last_purchase', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'active_campaigns', sa.JSON(), nullable=False),
                                                   sa.Column(
                                                       'devices', sa.JSON(), nullable=False),
                                                   sa.Column(
                                                       'level', sa.Integer(), nullable=False),
                                                   sa.Column(
                                                       'xp', sa.Integer(), nullable=False),
                                                   sa.Column(
                                                       'total_playtime', sa.Integer(), nullable=False),
                                                   sa.Column(
                                                       'country', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'language', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'birthdate', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'gender', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'inventory', sa.JSON(), nullable=False),
                                                   sa.Column(
                                                       'clan', sa.JSON(), nullable=False),
                                                   sa.Column(
                                                       '_customfield', sa.String(), nullable=False),
                                                   sa.Column(
                                                       'username', sa.String(), nullable=True),
                                                   sa.Column(
                                                       'email', sa.String(), nullable=True),
                                                   sa.Column('date_created', sa.DateTime(),
                                                             server_default=sa.text('now()'), nullable=False),
                                                   sa.Column('date_updated', sa.DateTime(),
                                                             server_default=sa.text('now()'), nullable=False),
                                                   sa.Column(
                                                       'date_deleted', sa.DateTime(), nullable=True),
                                                   sa.PrimaryKeyConstraint(
                                                       'id'),
                                                   sa.UniqueConstraint('id'),
                                                   sa.UniqueConstraint(
                                                       'player_id')
                                                   )

    # Insert mock data into the current_campaigns and player_profiles tables
    insert_current_campaigns_data(current_campaigns_table)
    insert_player_profiles_data(player_profiles_table)
    # ### end Alembic commands ###


def insert_current_campaigns_data(current_campaigns_table: Table) -> None:
    """Insert mock data into current_campaigns table."""

    with open(CURRENT_CAMPAIGNS_MOCK_DATA, 'r') as file:
        current_campaigns_data = json.load(file)
        op.bulk_insert(current_campaigns_table, current_campaigns_data)


def insert_player_profiles_data(player_profiles_table: Table) -> None:
    """Insert mock data into player_profiles table."""

    with open(PLAYER_PROFILES_MOCK_DATA, 'r') as file:
        player_profiles_data = json.load(file)
        op.bulk_insert(player_profiles_table, player_profiles_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_profiles')
    op.drop_table('current_campaigns')
    # ### end Alembic commands ###
