"""Create player profile and current campaign tables

Revision ID: 9ae330558137
Revises: 
Create Date: 2025-07-14 00:37:09.383482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae330558137'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=30), nullable=False),
    sa.Column('credential', sa.String(length=30), nullable=False),
    sa.Column('created', sa.String(length=30), nullable=False),
    sa.Column('modified', sa.String(length=30), nullable=False),
    sa.Column('last_session', sa.String(length=30), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('total_refund', sa.Float(), nullable=False),
    sa.Column('total_transactions', sa.Float(), nullable=False),
    sa.Column('last_purchase', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('total_playtime', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('birthdate', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('customfield', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_profiles')
    # ### end Alembic commands ###
